### ISSUE TITLE
Amy's journal

### ISSUE THREAD

**Issue by yaelago** [TheBreakingGoodProject/Dalyell-Projects#11]
Posting Amy's journal here, since she is having some trouble with her GitHub account.

NEW COMMENT 
### **Medicine 1: Rifabutin**
I have recently completed the entire set of challenges for the drug Rifabutin which has allowed me to not only familiarise with the process of this project, but to also learn about a drug that I have never heard of before. I found from a basic search on Google from [Medline Plus](https://medlineplus.gov/druginfo/meds/a693009.html) that the main purpose of Rifabutin is to treat patients with tuberculosis by slowing down or preventing the spread of a bacterial infection (Mycobacterium avium complex). It is also the alternative for Rifampin, particularly for patients with HIV.
 
### **Challenge 1 News Flash**
During challenge #1 News Flash, while conducting a Google search on any news related to rifabutin, the first [study](https://news.usc.edu/171273/acinetobacter-baumannii-superbug-treatment-rifabutin-antibiotic-usc-research/) I came across that was published last year in June  was conducted by researchers from the University of Southern California where rifabutin was being repurposed to treat _Acinetobacter Baumannii_. This is a multi-drug resistant infection that can lead to pneumonia and meningitis, which was accountable for about 2% of 99,000 deaths in the US (Centers for Disease Control and Prevention).
 
I found it quite interesting that the researchers realised that _A. baumannii_ and many superbugs couldn't be treated using Rifabutin. This was because they had used the traditional rich culture media to grow bacteria for antibiotic testing which didn't mimic our body's conditions. It became apparent to me that the medical community could potentially use this new screening method to identify new antibiotics for treatment which will be fundamental.
 
Now that I had a topic in mind for the News Flash challenge, I searched "rifabutin acinetobacter baumannii treatment" on Google to read more on it. However, many academic research papers were the top results so I decided to read mainly the abstract as majority of the paper had an overwhelming amount of unfamiliar terms that made it difficult to follow along.
 
### **Challenge 2 Price Hike$**
During **challenge #2 Price Hike$**, I followed the guide to aid my research process on the pricing of rifabutin. After searching "rifabutin price hike" on Google, the first page I came across was the NCBI site which I know is considered a reputable source for medical/science research ([Rockwood, Cerrone, Barber, Hill, Pozniak, 2019](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6637439/)). The journal focused on the accessibility of rifabutin which provided the relevant information for my investigation.
I found that rather than a price hike, rifabutin experienced a price decrease due to the removal of a patent. This information corroborates with another journal I found that stated this led to a 60 % reduction in cost for patients [(Carbol, Catherinot, Veziris, Jullien, Lortholary, 2016)](https://academic.oup.com/jac/article/71/7/1759/1750373). Clearly, this drug was prevented from widespread use due to its costs, which made me realise that this is a growing issue that many other medications have that we aren't aware of.
 
During the last part where we calculated the cost using the information from the [Pharmaceuticals Benefits Scheme](https://www.pbs.gov.au/medicine/item/6195C-9541E), I learnt that our medication is part of a system that give Australians access to medication. I found it to be very interesting and useful that the general prices patients are charged for each medication to be listed on the site.
For rifabutin, the cost for one unit of this medicine was $4.62 AUD based on calculations using the DPMQ ($554.62) and the max qty of units (120). With tuberculosis being quite common across the globe, it is clear that if the price was not reduced due to the removal of the patent, many patients would have not been able to afford this. I haven't been able to find much information regarding the prices in other countries, so it is unclear whether rifabutin is very accessible or not.
 
### **Challenge 3 Circle of Life**
This last challenge allowed me to learn more about how ownership over a medication works within the pharmaceutical industry. Although considered to be not the most reliable, wikipedia was used to guide potential searches as it had a good summary on the history of rifabutin. I found that rifabutin was first owned by Archifar in 1975, which I ensured was correct by visiting the [WHO document](https://www.who.int/3by5/en/patentshivdrugs.pdf) on drugs that were protected by US patents. On the Pfizer site, I learnt that [Pfizer](https://www.pfizer.com/about/history/pfizer_pharmacia) now owns Pharmacia and Upjohn which is a merger that currently holds the right to supply rifabutin. The public database on essential medicines also allowed me to learn that the trade name for rifabutin is Mycobutin which was approved by the FDA in 1992, as well as the important information to consider (e.g. route, applicant holder, trade name).
 
Overall, this first set of challenges has been a rewarding process for me to learn about rifabutin and the amount of detail to consider within the pharmaceutical industry.
 
 
 
 
 
 
 
NEW COMMENT 
 
### **Medicine 2: Insulin**
Recently, I learnt about the importance of maintaining our blood glucose levels and how the beta cells in our pancreas are central to type 1 and type 2 diabetes. This fuelled my interest in investigating further into insulin as a treatment for diabetic patients.
 
### **Challenge 1: News Flash**
Using Google, I searched for any recent news on insulin and found recent articles on a new type of medication to treat diabetes. The first article from [WebMD](https://www.webmd.com/diabetes/news/20210322/coming-soon-once-a-week-insulin-injections) announced that there is a new type of insulin treatment called basal insulin FC (BIF) where patients do not need to have daily injections of insulin, but instead can reduce it down to once-a-week. At this point in time, I was asking myself if this was reliable information or not...
To ensure the information was reliable, I went back to Google where I searched "weekly insulin injection" and found a journal from [the New England Journal of Medicine](https://www.nejm.org/doi/full/10.1056/nejmoa2022474). I considered this to be a reliable source as the website ended with '.org' and was published by researchers with expertise in the field. There I learnt that BIF is in fact in its trial stages and is considered to be as effective as daily insulin glargine U100 injections for patients with type 2 diabetes.
 
In this challenge, I learnt new knowledge on the current research being conducted to find more effective treatments for patients with type 2 diabetes. I was also conscious on the reliability of the sources I gathered my information from.
 
### **Challenge 2: Price Hike$**
When I was investigating the prices for insulin, according to a study conducted by a [RAND Corporation study](https://www.rand.org/news/press/2020/10/06.html), I found that the US had experienced price hikes 8 times higher compared to 32 high-income nations combined. So from this source, I started to research the reasons behind the high price for insulin.
 
I googled "insulin price hikes" and came across various sources which stated many different reasons for different types of insulin products. At this stage I was very confused.
First, I came across an article from [Business Insider](https://www.businessinsider.com.au/rising-insulin-prices-track-competitors-closely-2016-9) where I learnt that the major pharmaceutical suppliers for insulin were Sanofi, Novo Nordisk, and Eli Lilly & Co. They were accountable for the price hikes over the years due to intense competition which meant improvements were made in terms of packaging and production. They also experienced declining income due to rebates.
 
Another article from [Endocrine Society ](https://www.endocrine.org/advocacy/position-statements/increasing-insulin-affordability) stated that patients are paying very high prices due to variations in factors such as the insurance plan type, the type of insulin used, their deductible and where they are in the plan. I also learnt that some uninsured patients and patients with high deductible health plans end up paying the full price.
Additionally, it is also quite difficult for pharmacists to take into account these factors when choosing the type of insulin medication to use for the patients, which means they cannot be provided with the lowest cost alternative.
 
At this stage, I still did not clearly understand why the prices were increasing to this extent until I came across information from [Beyond Type 1](https://beyondtype1.org/insulin-pricing/), a non-profit organisation with a mission advocate and educate sufferers of diabetes. This site summarised how insulin pricing works in the US in a way that was not only easy to follow along, but it connected the dots for me!
I discovered that there are 4 major players behind the price hikes - the 3 major pharmaceutical companies (mentioned earlier), insurance companies, pharmacy benefit managers (PBS), and the government.
 
The pricing system for insulin is a very complex web of networks which I found to be well summarised in the diagram from Beyond Type 1 below:
 
![](https://beyondtype1.org/wp-content/uploads/2018/06/BT1-GRAPHIC-INSULIN-CHAIN-1.jpg)
 
I was surprised at first with the complexity of the supply chain behind the single transaction at the pharmacy, but with my studies in marketing I knew that this was true.
The main takeaways behind the pricing system that I learnt was that:
 
- The negotiations between pharmaceutical manufacturers and PBMs on pricing can significantly drive up costs for consumers without them knowing. Manufacturers pay a part of the listed price to the PBMs for their insulin product to be listed on the insurance plans for patients, which means that PBMs get a major discount on the medication if they list the product on the insurance plan. As such, there is major competition between pharmaceutical companies which has increased the list prices to PBMs, ultimately increasing costs for patients
- The many negotiation payments between wholesalers, pharmaceutical companies, pharmacies, PBMs changes the original cost since it left the manufacturer.
 
This challenge was difficult for me due to the complexity of the pricing system and gathering information to fully understand the big picture. In the future challenges, if I experience difficulty with finding the right information, I would consider researching from non-profit organisation websites that are targeted for patients suffering from a particular disease/illness. They are less likely to provide false information, especially if they end with '.org' and the information is conveyed in a way that is easy to understand.
 
### **Challenge 3: Circle of Life**
For this challenge, I learnt through the database that there is an extensive list of different types of insulin treatments which are based on the strength, dosage form (e.g. injection, powder) and how it is administered (e.g. subcutaneous, intravenous, inhalation).
I chose to research Admelog owned by Sanofi-Aventis US LLC, where I learnt that Sanofi is one of the major companies in the pharmaceutical industry.
I found it interesting to read the history of insulin from the [American Diabetes Association](https://www.diabetes.org/blog/history-wonderful-thing-we-call-insulin), where I learnt that before insulin treatments were developed, a patient diagnosed with diabetes meant they didn't have much time left. This made me reflect upon the significant achievements within the medical community, and the importance of transparency behind the reasons why insulin treatments are so non-accessible.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

 
 NEW COMMENT 
 
### **Medicine 3: Ivermectin**
For the next medicine, I decided to investigate Ivermectin, one that I have no knowledge of. Some information on Ivermectin from a basic Google search, is that it is an anti-parasitic drug used to treat conditions such as head lice, scabies and parasitic worms.
 
### **Challenge 1: News Flash**
To find current news on ivermectin, I went on the Google news tab and found many articles stating that ivermectin may be used as a cure for COVID-19. This piqued my interest with the different perspectives.
Now that I knew how to find reliable information based on experience from my previous challenges, I searched for articles on this topic with URLs ending with '.org' or '.gov'.
According to [NPS MedicineWise](https://www.nps.org.au/ivermectin-and-covid-19), I discovered that Australian researchers since April 2020 found that ivermectin could stop the the SARS-CoV-2 virus from multiplying under animal cells. Although there has been some "success" in using ivermectin as a treatment, there are doubts surrounding whether this could be a cure for COVID-19.  After reading this page, I learnt about the different kinds of questions scientists should always consider when repurposing medicine; What is a safe dose to use?
Should other medicines be used as well?
 
### **Challenge 2: Price Hike$**
For this challenge, I found it quite difficult to find price increases or decreases for ivermectin from a reliable website. Based off the [PBS site](https://www.pbs.gov.au/medicine/item/2868Y-8359Y), the price per unit of ivermectin is $5.90 after calculations. As I could not find evidence of price hikes within Australia, I made an assumption here that there wasn't any price increases.
 
However, I did come across news articles that stated there were price hikes in South Africa and India after searching "ivermectin price increase" on Google. I did question whether the information was trustworthy as I could not find other reliable websites to corroborate it.
According to [IOL](https://www.iol.co.za/news/politics/blame-government-for-black-market-ivermectin-boom-says-doctor-b3655b1a-178c-4434-9a59-85d02d7ee1c0), I found that ivermectin allegedly increased from R10 to around R250 - R500 per pill on the black market (since ivermectin is illegal for human use which has now been lifted of its ban when the government responded to this out-of-control issue). The article provides an explanation that the government is to be blamed for this illegal selling as they restricted the use of an anti-parasitic drug that has been proven effective for parasitic diseases.
 
The information that I found in this challenge for ivermectin was quite different to the previous medicines I researched as the price hike occurred illegally. It has brought a major issue to my attention i.e. every country has different legal restrictions regarding pharmaceutical drugs and this has a significant impact on the people as many sought to illegal activities out of desperation especially during a pandemic. I have learnt here that issues surrounding medicine accessibility are not only financial, but can also be determined by legal, political, and social problems.
 
### **Challenge 3: Circle of Life**
From this challenge, I mainly gained new knowledge on the history behind ivermectin and how it was prohibited for human use  for a long time until 1987 where it was sold under the name Mectizan.
I investigated Stromectol which is currently owned by Merck Sharp and Dohme Corp, a subsidiary of Merck & Co. This was the first company that owned ivermectin.
It was interesting to read about the collaboration between Japanese researcher Satoshi Oomura who sent the best samples of compounds found in Japanese soil with their cultured bacteria to William C. Campbell in the Merck Research Labs, New Jersey. Together, they discovered ivermectin was effective to use for livestock ([American Chemical Society, 2016](https://www.acs.org/content/acs/en/education/whatischemistry/landmarks/ivermectin-mectizan.html)). Learning about the discovery of ivermectin made me reflect upon the importance of effective communication and collaboration within the science community to make progress in areas with gaps, which is the essence of this project!
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 NEW COMMENT 
 
### **Medicine 4: Fluoxetine**
This time round, I wanted to research a medicine that is quite different to the other ones I have investigated so far. Fluoxetine is an anti-depressant used to treat a wide range of mental health conditions such as major depressive disorder, obsessive–compulsive disorder, bulimia nervosa, panic disorder, and premenstrual dysphoric disorder.
 
### **Challenge 1: News Flash**
The most recent news that I could find on fluoxetine were related to COVID-19.
According to the [University of Toledo](http://news.utoledo.edu/index.php/02_19_2021/common-antidepressant-may-reduce-deadly-covid-19-complications), fluoxetine may not help with preventing people from getting sick with COVID-19, but it can help with preventing people from becoming seriously ill, including hospitalisation, intubation, death.
This was quite surprising to me as this was the second medicine that I've researched which is currently being repurposed for COVID-19. Here I learnt that many unexpected medicines that supposedly are not associated with the coronavirus (in this case for mental health conditions) can be repurposed for it.
As I was quite interested in reading more about this topic, I searched further on Google and came across an article on NCBI which discussed the interactions of psychiatric and COVID-19 medication [(Mohebbi, Talebi, Moghadamnia, Nazari Taloki, Shakiba, 2020).](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7368108/). It was difficult for me to read most of the journal due to the unfamiliar terminology, but nonetheless I was able to extract the key message. I learnt that there are many consequences that need to be considered when a patient takes both psychiatric  and COVID-19 medication, such as the rise in mental health issues with the pandemic.
Reading these articles and journals definitely emphasised the importance of debates within the scientific/medical community for there to be progress and a better outcome.
 
### **Challenge 2: Price Hike$**
I found it quite difficult to find reliable sources/websites for information regarding price hikes. However, I did come across a few sites such as one from [ARS Technica ](https://arstechnica.com/science/2019/10/new-drug-pricing-data-shows-stunning-hikes-one-whopping-667-increase/#:~:text=A%20liquid%20versi20of%20generic,given%20was%20new%20production%20costs.) that detailed the price hikes for fluoxetine in California during 2019 when a transparency law was passed which meant drug makers were required to report their price increases quarterly and the reasons behind. This brought the issue on the lack of transparency within business practices to my attention, which definitely is concerning especially when it limits the access of essential medicines to vulnerable groups.
 
### **Challenge 3: Circle of Life**
During this challenge, I did not learn anything new as it has been similar to the previous times I completed this for the previous medicines. I mainly gained new knowledge in terms of the history behind fluoxetine. I found through that fluoxetine was released into the market in 1987 under the name Prozac after approval by the FDA [ (Hillhouse, Todd, and Joseph, 2015).](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4428540/#:~:text=Fluoxetine%20was%20approved%20by%20the,%2C%20%26%20Bymaster%2C%202005).)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 NEW COMMENT 
###  **Medicine 5: Levonorgestrel**
I decided to choose levonorgestrel as I wanted to investigate a medicine that was different in terms of function and purpose to the ones I had previously researched. I also was interested in this medicine as I had no knowledge of it. Levonorgestrel is used by women to prevent pregnancy after they fail birth control methods, which is only used for emergency purposes and not on a regular basis for contraception.
 
### **Challenge 1: News Flash**
I found that this challenge was more difficult compared to the previous medications as I struggled to find news that were relevant to the topics in the list to choose from. Usually the news tab on Google would give me an overall idea of the current news related to medication which guides me with further research into the topic. However, for levonorgestrel, many of the articles were related to its performance in the market which weren't relevant. Eventually after scrolling through a few pages under the term "levonorgestrel news", the news article that I came across on [Endocrine News](https://endocrinenews.endocrine.org/august-2014-pregnant-pause/) focused on the side effects or lack of efficacy when taking this medicine. Studies have shown that women weighing about 165 pounds experience reduced efficacy with the levonorgestrel contraception, and it does not work at all for women weighing 175 pounds or more. To address this issue, there has been a change in the patient information packets of the European levonorgestrel EC to inform women of its lack of efficacy in overweight and obese women. The FDA is also  considering a change to U.S. labels.
 
When the article stated that "most women are still unaware of the drug’s limited efficacy", this emphasised that the lack of access to information is a predominant issue within the general population. It was a good reminder of why we are undertaking this project and how important it is to learn about how the general population accesses information on medication for the scientific community to effectively communicate insights and misconceptions.
 
 
### **Challenge 2: Price Hike$**
For challenge 2, I found it quite difficult to obtain concrete information on a price increase for levonorgestrel from a reliable source. After searching different terms such as "levonorgestrel price hike", "levonorgestrel price increase", "levonorgestrel price change", and "levonorgestrel cost", I mainly saw articles stating that there were price increases over the years rather than a price decrease.
Although I was quite sceptical of whether the information was reliable or not based on what I learnt in previous challenges (e.g. URLs end with 'gov', 'edu', and 'org'), these were the sources I could find that mentioned price hikes. According to[ iNews](https://inews.co.uk/news/health/morning-pill-manufacturers-criticised-hiking-price-150-per-cent-129126), the UK experienced price hikes from £2.87 in January 2017 up to £4.33 by December 2017. I didn't manage to find any information on the reason behind the price increase, but based on the different prices for each retailer, I deduced that the pricing of levonorgestrel is highly varied.
 
In a report from the [American Society of Emergency Contraception (ASECP) ](https://ec.princeton.edu/ASECPricingReport.pdf) on "the Cost of Emergency Contraception", I found that the average price for branded products such as Plan B One-Step is $48 USD whereas generic EC products cost only 14% less, at an average of $41. Clearly, the pricing of levonorgestrel and whether it is increases is dependent on multiple factors including the brand (e.g. generic vs branded), insurance coverage, type of medication and where the customer purchases it from.
 
I also added to my knowledge on the pricing system in the US which I had researched earlier for insulin. The report from ASECP stated that pricing changes between negotiations, whereby the price can be expected to increase before reaching the consumer. The Wholesale Acquisition Cost (WAC) is an
estimate of the manufacturer’s list price to wholesalers and other bulk purchasers which may be discounted by
rebates or incentives.
 
Overall, in this challenge, I learnt that price hikes are not clear but if they did  occur, they are dependent on multiple factors.
 
### **Challenge 3: Circle of Life**
I found it quite difficult in this challenge to research from a reliable source the first owner  and any important events regarding levonorgestrel formal website. I mainly ended up obtaining the necessary information from [Britannica](https://www.britannica.com/science/levonorgestrel) on the first owner which was Norplant in the early 1980s. I also learnt some new knowledge on the history behind levonorgestrel, including the name changes behind them.

**Comment by ShirleyZ11** [comment]
Hi Amy,

Reading through the experiences you had whilst completing the challenges, I can see that we had similar experiences and in fact chose similar medicines to research as well. Your entries allowed me to understand the various medicines from a different perspective, because I noticed in some cases we had actually found different information on the same medicine. Since this suggests that there are various sources of information for the same topic, this made me consider how one can determine what is the most accurate information even if they are all taken from reliable sources. It would be interesting to see the difference between our researching techniques and how this lead to varying results. 

Like you, I found the price hike challenge more difficult and thought that it lacked some direction. Perhaps if there were more resources available for researching price hikes, or if the questions were more specific (e.g. limited to a certain country) it may have been easier to find information surrounding this. 

I really enjoyed reading your entries because I already had an understanding of these medicines (from my own experience with the task) and your research on them allowed me to expand on that knowledge. It was interesting to see how although our learning processes were similar, the information we found differed. Maybe that has something to do with the way we learnt from our individual experiences? 

I'm looking forward to working together on our final group project and seeing what we create :))
