### ISSUE TITLE
Hi I'm Jasmine!

### ISSUE THREAD

**Issue by jasmineusyd** [TheBreakingGoodProject/Dalyell-Projects#5]
Hi everyone! I'm studying a B of Science and B of Adv Studies in Genetics and Cell Biology! I look forward to meeting and working with you all. I chose this project because I have experienced first hand the challenges and grievances of the outrageous and unequal price of medication and other pharmaceutical goods. I am very interested to learn about how and why different medications are priced as well as how we can draw further attention to this issue and research in general from the public. I also look forward to working with professionals and mentors in the industry to gain a more sophisticated understanding of the pharmaceutical industry along with the rest of my group members!

**Comment by yaelago** [comment]
Welcome Jasmine!
It's great having you onboard, and we are looking forward to hearing about your journey and learning processes. 
It's difficult reflecting on our own experiences, but this is also an opportunity to grow and create change. We would love to learn from your experiences through the NewsFlash challenge and also hear how engaging with E$$ential medicinE$ made you feel.
